<?php

namespace Database\Seeders;

use App\Models\LessonPlan;
use App\Models\SchoolClass;
use Illuminate\Database\Seeder;

class LessonPlanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // school_classes.codeはクラスごとに一意なので、それぞれ1件ずつ取得すればよい
        $classA1 = SchoolClass::where('code', 'A1')->firstOrFail();
        $classA2 = SchoolClass::where('code', 'A2')->firstOrFail();
        $classA3 = SchoolClass::where('code', 'A3')->firstOrFail();
        $classB1 = SchoolClass::where('code', 'B1')->firstOrFail();
        $classB2 = SchoolClass::where('code', 'B2')->firstOrFail();
        $classB3 = SchoolClass::where('code', 'B3')->firstOrFail();
        $classB4 = SchoolClass::where('code', 'B4')->firstOrFail();
        $classB5 = SchoolClass::where('code', 'B5')->firstOrFail();
        $classB6 = SchoolClass::where('code', 'B6')->firstOrFail();

        $lessonPlans = [
            // A1クラス（基礎クラス1組）
            // 1学期
            ['school_class_id' => $classA1->id, 'no' => 1, 'title' => 'プログラミングってなあに？さわってあそぼう'],
            ['school_class_id' => $classA1->id, 'no' => 2, 'title' => 'じゅんばんどおりにうごかそう①'],
            ['school_class_id' => $classA1->id, 'no' => 3, 'title' => 'じゅんばんどおりにうごかそう②'],
            ['school_class_id' => $classA1->id, 'no' => 4, 'title' => 'くりかえしてみよう①（ぐるぐるダンス）'],
            ['school_class_id' => $classA1->id, 'no' => 5, 'title' => 'くりかえしてみよう②'],
            ['school_class_id' => $classA1->id, 'no' => 6, 'title' => 'いろとかたちであそぼう'],
            ['school_class_id' => $classA1->id, 'no' => 7, 'title' => 'めいろをすすもう①'],
            ['school_class_id' => $classA1->id, 'no' => 8, 'title' => 'めいろをすすもう②'],
            ['school_class_id' => $classA1->id, 'no' => 9, 'title' => 'うごくえをかいてみよう①'],
            ['school_class_id' => $classA1->id, 'no' => 10, 'title' => 'うごくえをかいてみよう②'],
            ['school_class_id' => $classA1->id, 'no' => 11, 'title' => 'おとをつけてみよう'],
            ['school_class_id' => $classA1->id, 'no' => 12, 'title' => 'もしも〜だったら？を体験しよう①'],
            ['school_class_id' => $classA1->id, 'no' => 13, 'title' => 'もしも〜だったら？を体験しよう②'],
            ['school_class_id' => $classA1->id, 'no' => 14, 'title' => 'じぶんだけのおはなしをつくろう'],
            ['school_class_id' => $classA1->id, 'no' => 15, 'title' => '1学期のはっぴょうかい'],
            // 2学期
            ['school_class_id' => $classA1->id, 'no' => 16, 'title' => 'なつやすみのできごとをプログラムにしよう'],
            ['school_class_id' => $classA1->id, 'no' => 17, 'title' => 'うみのいきものをうごかそう①'],
            ['school_class_id' => $classA1->id, 'no' => 18, 'title' => 'うみのいきものをうごかそう②'],
            ['school_class_id' => $classA1->id, 'no' => 19, 'title' => 'のりものレースをつくろう①'],
            ['school_class_id' => $classA1->id, 'no' => 20, 'title' => 'のりものレースをつくろう②'],
            ['school_class_id' => $classA1->id, 'no' => 21, 'title' => 'くりかえしとじゅんばんのふくしゅう'],
            ['school_class_id' => $classA1->id, 'no' => 22, 'title' => 'どうぶつえんをつくろう①'],
            ['school_class_id' => $classA1->id, 'no' => 23, 'title' => 'どうぶつえんをつくろう②'],
            ['school_class_id' => $classA1->id, 'no' => 24, 'title' => 'おばけやしきをつくろう①（ハロウィン）'],
            ['school_class_id' => $classA1->id, 'no' => 25, 'title' => 'おばけやしきをつくろう②'],
            ['school_class_id' => $classA1->id, 'no' => 26, 'title' => 'スイッチでうごかしてみよう'],
            ['school_class_id' => $classA1->id, 'no' => 27, 'title' => 'じぶんのアイコンをつくろう'],
            ['school_class_id' => $classA1->id, 'no' => 28, 'title' => 'クリスマスのおはなしをつくろう①'],
            ['school_class_id' => $classA1->id, 'no' => 29, 'title' => 'クリスマスのおはなしをつくろう②'],
            ['school_class_id' => $classA1->id, 'no' => 30, 'title' => 'たのしいくりかえしゲーム'],
            ['school_class_id' => $classA1->id, 'no' => 31, 'title' => 'みんなでつくったさくひんをみせあおう'],
            ['school_class_id' => $classA1->id, 'no' => 32, 'title' => '2学期のはっぴょうかい'],
            // 3学期
            ['school_class_id' => $classA1->id, 'no' => 33, 'title' => 'おしょうがつのおはなしをつくろう'],
            ['school_class_id' => $classA1->id, 'no' => 34, 'title' => 'ふゆのけしきをうごかそう'],
            ['school_class_id' => $classA1->id, 'no' => 35, 'title' => 'もしも〜だったらゲーム①'],
            ['school_class_id' => $classA1->id, 'no' => 36, 'title' => 'もしも〜だったらゲーム②'],
            ['school_class_id' => $classA1->id, 'no' => 37, 'title' => 'じぶんだけのゲームをつくろう①'],
            ['school_class_id' => $classA1->id, 'no' => 38, 'title' => 'じぶんだけのゲームをつくろう②'],
            ['school_class_id' => $classA1->id, 'no' => 39, 'title' => 'じぶんだけのゲームをつくろう③'],
            ['school_class_id' => $classA1->id, 'no' => 40, 'title' => 'はっぴょうのれんしゅう'],
            ['school_class_id' => $classA1->id, 'no' => 41, 'title' => '1年間のふりかえり'],
            ['school_class_id' => $classA1->id, 'no' => 42, 'title' => '1年間のはっぴょうかい'],
            // A2クラス（基礎クラス2組）
            // 1学期
            ['school_class_id' => $classA2->id, 'no' => 1, 'title' => 'スクラッチをつかってみよう（はじめの一歩）'],
            ['school_class_id' => $classA2->id, 'no' => 2, 'title' => 'ねこをうごかそう①（じゅんじょ）'],
            ['school_class_id' => $classA2->id, 'no' => 3, 'title' => 'ねこをうごかそう②（キー操作）'],
            ['school_class_id' => $classA2->id, 'no' => 4, 'title' => 'くりかえしブロックをつかおう①'],
            ['school_class_id' => $classA2->id, 'no' => 5, 'title' => 'くりかえしブロックをつかおう②'],
            ['school_class_id' => $classA2->id, 'no' => 6, 'title' => 'おとをならそう'],
            ['school_class_id' => $classA2->id, 'no' => 7, 'title' => 'コスチュームをかえてアニメをつくろう'],
            ['school_class_id' => $classA2->id, 'no' => 8, 'title' => '自分だけのキャラクターをつくろう'],
            ['school_class_id' => $classA2->id, 'no' => 9, 'title' => 'めいろゲームをつくろう①'],
            ['school_class_id' => $classA2->id, 'no' => 10, 'title' => 'めいろゲームをつくろう②'],
            ['school_class_id' => $classA2->id, 'no' => 11, 'title' => 'あたり・はずれゲームをつくろう①'],
            ['school_class_id' => $classA2->id, 'no' => 12, 'title' => 'あたり・はずれゲームをつくろう②'],
            ['school_class_id' => $classA2->id, 'no' => 13, 'title' => '背景をデザインしよう'],
            ['school_class_id' => $classA2->id, 'no' => 14, 'title' => '1学期のさくひんをしあげよう'],
            ['school_class_id' => $classA2->id, 'no' => 15, 'title' => '1学期はっぴょう会'],
            // 2学期
            ['school_class_id' => $classA2->id, 'no' => 16, 'title' => '夏のおもいでゲームをつくろう'],
            ['school_class_id' => $classA2->id, 'no' => 17, 'title' => '「もし〜なら」ブロックをつかおう①（条件分岐入門）'],
            ['school_class_id' => $classA2->id, 'no' => 18, 'title' => '「もし〜なら」ブロックをつかおう②'],
            ['school_class_id' => $classA2->id, 'no' => 19, 'title' => 'シューティングゲームをつくろう①'],
            ['school_class_id' => $classA2->id, 'no' => 20, 'title' => 'シューティングゲームをつくろう②'],
            ['school_class_id' => $classA2->id, 'no' => 21, 'title' => 'シューティングゲームをつくろう③'],
            ['school_class_id' => $classA2->id, 'no' => 22, 'title' => 'スコアをかぞえよう（変数入門）'],
            ['school_class_id' => $classA2->id, 'no' => 23, 'title' => 'タイマーをつけよう'],
            ['school_class_id' => $classA2->id, 'no' => 24, 'title' => 'ハロウィンおばけゲームをつくろう①'],
            ['school_class_id' => $classA2->id, 'no' => 25, 'title' => 'ハロウィンおばけゲームをつくろう②'],
            ['school_class_id' => $classA2->id, 'no' => 26, 'title' => '音楽にあわせてうごくアニメをつくろう'],
            ['school_class_id' => $classA2->id, 'no' => 27, 'title' => 'すごろくゲームをつくろう①'],
            ['school_class_id' => $classA2->id, 'no' => 28, 'title' => 'すごろくゲームをつくろう②'],
            ['school_class_id' => $classA2->id, 'no' => 29, 'title' => 'クリスマスカードをつくろう①'],
            ['school_class_id' => $classA2->id, 'no' => 30, 'title' => 'クリスマスカードをつくろう②'],
            ['school_class_id' => $classA2->id, 'no' => 31, 'title' => '2学期のさくひんをしあげよう'],
            ['school_class_id' => $classA2->id, 'no' => 32, 'title' => '2学期はっぴょう会'],
            // 3学期
            ['school_class_id' => $classA2->id, 'no' => 33, 'title' => '新年のあいさつカードをつくろう'],
            ['school_class_id' => $classA2->id, 'no' => 34, 'title' => 'くりかえしと条件のふくしゅう'],
            ['school_class_id' => $classA2->id, 'no' => 35, 'title' => 'オリジナルゲームをつくろう①（きかくをかんがえよう）'],
            ['school_class_id' => $classA2->id, 'no' => 36, 'title' => 'オリジナルゲームをつくろう②'],
            ['school_class_id' => $classA2->id, 'no' => 37, 'title' => 'オリジナルゲームをつくろう③'],
            ['school_class_id' => $classA2->id, 'no' => 38, 'title' => 'オリジナルゲームをつくろう④'],
            ['school_class_id' => $classA2->id, 'no' => 39, 'title' => 'バグをなおそう（デバッグに挑戦）'],
            ['school_class_id' => $classA2->id, 'no' => 40, 'title' => 'はっぴょうのじゅんびをしよう'],
            ['school_class_id' => $classA2->id, 'no' => 41, 'title' => '1年間のふりかえり'],
            ['school_class_id' => $classA2->id, 'no' => 42, 'title' => '1年間の集大成はっぴょう会'],
            // A3クラス（基礎クラス3組）
            // 1学期
            ['school_class_id' => $classA3->id, 'no' => 1, 'title' => '1年間の流れを確認しよう＆スクラッチ復習'],
            ['school_class_id' => $classA3->id, 'no' => 2, 'title' => '変数をつかってみよう①（スコア表示）'],
            ['school_class_id' => $classA3->id, 'no' => 3, 'title' => '変数をつかってみよう②'],
            ['school_class_id' => $classA3->id, 'no' => 4, 'title' => '「もし〜なら〜でなければ」（条件分岐）①'],
            ['school_class_id' => $classA3->id, 'no' => 5, 'title' => '「もし〜なら〜でなければ」（条件分岐）②'],
            ['school_class_id' => $classA3->id, 'no' => 6, 'title' => 'キャッチゲームをつくろう①'],
            ['school_class_id' => $classA3->id, 'no' => 7, 'title' => 'キャッチゲームをつくろう②'],
            ['school_class_id' => $classA3->id, 'no' => 8, 'title' => '乱数をつかってみよう（ランダムのふしぎ）'],
            ['school_class_id' => $classA3->id, 'no' => 9, 'title' => 'アクションゲームをつくろう①'],
            ['school_class_id' => $classA3->id, 'no' => 10, 'title' => 'アクションゲームをつくろう②'],
            ['school_class_id' => $classA3->id, 'no' => 11, 'title' => 'アクションゲームをつくろう③'],
            ['school_class_id' => $classA3->id, 'no' => 12, 'title' => '複数のキャラクターを動かそう'],
            ['school_class_id' => $classA3->id, 'no' => 13, 'title' => 'サウンドとエフェクトをこだわろう'],
            ['school_class_id' => $classA3->id, 'no' => 14, 'title' => '1学期の作品を仕上げよう'],
            ['school_class_id' => $classA3->id, 'no' => 15, 'title' => '1学期発表会'],
            // 2学期
            ['school_class_id' => $classA3->id, 'no' => 16, 'title' => '夏休みの思い出をゲームにしよう'],
            ['school_class_id' => $classA3->id, 'no' => 17, 'title' => '図形を描くプログラムに挑戦①（ペン機能）'],
            ['school_class_id' => $classA3->id, 'no' => 18, 'title' => '図形を描くプログラムに挑戦②'],
            ['school_class_id' => $classA3->id, 'no' => 19, 'title' => '迷路ゲームをつくろう①（複雑な条件分岐）'],
            ['school_class_id' => $classA3->id, 'no' => 20, 'title' => '迷路ゲームをつくろう②'],
            ['school_class_id' => $classA3->id, 'no' => 21, 'title' => '迷路ゲームをつくろう③'],
            ['school_class_id' => $classA3->id, 'no' => 22, 'title' => 'タイマー＆スコアを組み合わせよう'],
            ['school_class_id' => $classA3->id, 'no' => 23, 'title' => 'ハロウィンアクションゲームをつくろう①'],
            ['school_class_id' => $classA3->id, 'no' => 24, 'title' => 'ハロウィンアクションゲームをつくろう②'],
            ['school_class_id' => $classA3->id, 'no' => 25, 'title' => '敵キャラクターのうごきを工夫しよう'],
            ['school_class_id' => $classA3->id, 'no' => 26, 'title' => 'クローン機能を使ってみよう①'],
            ['school_class_id' => $classA3->id, 'no' => 27, 'title' => 'クローン機能を使ってみよう②'],
            ['school_class_id' => $classA3->id, 'no' => 28, 'title' => 'シューティングゲームをつくろう①'],
            ['school_class_id' => $classA3->id, 'no' => 29, 'title' => 'シューティングゲームをつくろう②'],
            ['school_class_id' => $classA3->id, 'no' => 30, 'title' => 'クリスマスイベントをつくろう'],
            ['school_class_id' => $classA3->id, 'no' => 31, 'title' => '2学期の作品を仕上げよう'],
            ['school_class_id' => $classA3->id, 'no' => 32, 'title' => '2学期発表会'],
            // 3学期
            ['school_class_id' => $classA3->id, 'no' => 33, 'title' => '新年ミニゲームをつくろう'],
            ['school_class_id' => $classA3->id, 'no' => 34, 'title' => '変数と条件分岐の総復習'],
            ['school_class_id' => $classA3->id, 'no' => 35, 'title' => 'オリジナルゲーム企画会議'],
            ['school_class_id' => $classA3->id, 'no' => 36, 'title' => 'オリジナルゲームづくり①'],
            ['school_class_id' => $classA3->id, 'no' => 37, 'title' => 'オリジナルゲームづくり②'],
            ['school_class_id' => $classA3->id, 'no' => 38, 'title' => 'オリジナルゲームづくり③'],
            ['school_class_id' => $classA3->id, 'no' => 39, 'title' => 'オリジナルゲームづくり④'],
            ['school_class_id' => $classA3->id, 'no' => 40, 'title' => '発表準備＆リハーサル'],
            ['school_class_id' => $classA3->id, 'no' => 41, 'title' => '1年間のふりかえり'],
            ['school_class_id' => $classA3->id, 'no' => 42, 'title' => '1年間の集大成発表会'],
            // B1クラス（応用クラス1組）
            // 1学期
            ['school_class_id' => $classB1->id, 'no' => 1, 'title' => '応用クラスへようこそ！スクラッチ総復習'],
            ['school_class_id' => $classB1->id, 'no' => 2, 'title' => '変数をつかいこなそう①（スコア・タイマー）'],
            ['school_class_id' => $classB1->id, 'no' => 3, 'title' => '変数をつかいこなそう②'],
            ['school_class_id' => $classB1->id, 'no' => 4, 'title' => '条件分岐を組み合わせよう①'],
            ['school_class_id' => $classB1->id, 'no' => 5, 'title' => '条件分岐を組み合わせよう②'],
            ['school_class_id' => $classB1->id, 'no' => 6, 'title' => 'キャッチゲームをつくろう①'],
            ['school_class_id' => $classB1->id, 'no' => 7, 'title' => 'キャッチゲームをつくろう②'],
            ['school_class_id' => $classB1->id, 'no' => 8, 'title' => '乱数でオリジナル要素を加えよう'],
            ['school_class_id' => $classB1->id, 'no' => 9, 'title' => 'アクションゲームをつくろう①'],
            ['school_class_id' => $classB1->id, 'no' => 10, 'title' => 'アクションゲームをつくろう②'],
            ['school_class_id' => $classB1->id, 'no' => 11, 'title' => 'アクションゲームをつくろう③'],
            ['school_class_id' => $classB1->id, 'no' => 12, 'title' => '複数キャラクターを動かそう'],
            ['school_class_id' => $classB1->id, 'no' => 13, 'title' => 'サウンド・エフェクトで演出しよう'],
            ['school_class_id' => $classB1->id, 'no' => 14, 'title' => '1学期の作品を仕上げよう'],
            ['school_class_id' => $classB1->id, 'no' => 15, 'title' => '1学期発表会'],
            // 2学期
            ['school_class_id' => $classB1->id, 'no' => 16, 'title' => '夏休みの思い出をゲームにしよう'],
            ['school_class_id' => $classB1->id, 'no' => 17, 'title' => 'ペン機能で図形を描こう①'],
            ['school_class_id' => $classB1->id, 'no' => 18, 'title' => 'ペン機能で図形を描こう②'],
            ['school_class_id' => $classB1->id, 'no' => 19, 'title' => '迷路ゲームをつくろう①'],
            ['school_class_id' => $classB1->id, 'no' => 20, 'title' => '迷路ゲームをつくろう②'],
            ['school_class_id' => $classB1->id, 'no' => 21, 'title' => '迷路ゲームをつくろう③'],
            ['school_class_id' => $classB1->id, 'no' => 22, 'title' => 'タイマー＆スコアを組み合わせよう'],
            ['school_class_id' => $classB1->id, 'no' => 23, 'title' => 'ハロウィンアクションゲームをつくろう①'],
            ['school_class_id' => $classB1->id, 'no' => 24, 'title' => 'ハロウィンアクションゲームをつくろう②'],
            ['school_class_id' => $classB1->id, 'no' => 25, 'title' => '敵キャラクターの動きを工夫しよう'],
            ['school_class_id' => $classB1->id, 'no' => 26, 'title' => 'クローン機能を使ってみよう①'],
            ['school_class_id' => $classB1->id, 'no' => 27, 'title' => 'クローン機能を使ってみよう②'],
            ['school_class_id' => $classB1->id, 'no' => 28, 'title' => 'シューティングゲームをつくろう①'],
            ['school_class_id' => $classB1->id, 'no' => 29, 'title' => 'シューティングゲームをつくろう②'],
            ['school_class_id' => $classB1->id, 'no' => 30, 'title' => 'クリスマスイベントをつくろう'],
            ['school_class_id' => $classB1->id, 'no' => 31, 'title' => '2学期の作品を仕上げよう'],
            ['school_class_id' => $classB1->id, 'no' => 32, 'title' => '2学期発表会'],
            // 3学期
            ['school_class_id' => $classB1->id, 'no' => 33, 'title' => '新年ミニゲームをつくろう'],
            ['school_class_id' => $classB1->id, 'no' => 34, 'title' => '変数と条件分岐の総復習'],
            ['school_class_id' => $classB1->id, 'no' => 35, 'title' => 'オリジナルゲーム企画会議'],
            ['school_class_id' => $classB1->id, 'no' => 36, 'title' => 'オリジナルゲームづくり①'],
            ['school_class_id' => $classB1->id, 'no' => 37, 'title' => 'オリジナルゲームづくり②'],
            ['school_class_id' => $classB1->id, 'no' => 38, 'title' => 'オリジナルゲームづくり③'],
            ['school_class_id' => $classB1->id, 'no' => 39, 'title' => 'オリジナルゲームづくり④'],
            ['school_class_id' => $classB1->id, 'no' => 40, 'title' => '発表準備＆リハーサル'],
            ['school_class_id' => $classB1->id, 'no' => 41, 'title' => '1年間のふりかえり'],
            ['school_class_id' => $classB1->id, 'no' => 42, 'title' => '1年間の集大成発表会'],
            // B2クラス（応用クラス2組）
            // 1学期
            ['school_class_id' => $classB2->id, 'no' => 1, 'title' => '応用クラス2組オリエンテーション＆スクラッチ再確認'],
            ['school_class_id' => $classB2->id, 'no' => 2, 'title' => 'リスト（配列）を使ってみよう①'],
            ['school_class_id' => $classB2->id, 'no' => 3, 'title' => 'リスト（配列）を使ってみよう②'],
            ['school_class_id' => $classB2->id, 'no' => 4, 'title' => 'リストを使ったスコアボードをつくろう'],
            ['school_class_id' => $classB2->id, 'no' => 5, 'title' => '複数スプライトを連携させよう①'],
            ['school_class_id' => $classB2->id, 'no' => 6, 'title' => '複数スプライトを連携させよう②'],
            ['school_class_id' => $classB2->id, 'no' => 7, 'title' => '条件分岐を組み合わせたゲームロジック①'],
            ['school_class_id' => $classB2->id, 'no' => 8, 'title' => '条件分岐を組み合わせたゲームロジック②'],
            ['school_class_id' => $classB2->id, 'no' => 9, 'title' => 'シューティングゲームをつくろう①'],
            ['school_class_id' => $classB2->id, 'no' => 10, 'title' => 'シューティングゲームをつくろう②'],
            ['school_class_id' => $classB2->id, 'no' => 11, 'title' => 'シューティングゲームをつくろう③'],
            ['school_class_id' => $classB2->id, 'no' => 12, 'title' => 'アイテム収集ゲームをつくろう①'],
            ['school_class_id' => $classB2->id, 'no' => 13, 'title' => 'アイテム収集ゲームをつくろう②'],
            ['school_class_id' => $classB2->id, 'no' => 14, 'title' => '1学期の作品を仕上げよう'],
            ['school_class_id' => $classB2->id, 'no' => 15, 'title' => '1学期発表会'],
            // 2学期
            ['school_class_id' => $classB2->id, 'no' => 16, 'title' => '夏休みの思い出をリストで記録しよう'],
            ['school_class_id' => $classB2->id, 'no' => 17, 'title' => 'マイブロック（自分だけのブロック）に挑戦①'],
            ['school_class_id' => $classB2->id, 'no' => 18, 'title' => 'マイブロック（自分だけのブロック）に挑戦②'],
            ['school_class_id' => $classB2->id, 'no' => 19, 'title' => 'ミニRPGをつくろう①'],
            ['school_class_id' => $classB2->id, 'no' => 20, 'title' => 'ミニRPGをつくろう②'],
            ['school_class_id' => $classB2->id, 'no' => 21, 'title' => 'ミニRPGをつくろう③'],
            ['school_class_id' => $classB2->id, 'no' => 22, 'title' => 'ミニRPGをつくろう④'],
            ['school_class_id' => $classB2->id, 'no' => 23, 'title' => 'ハロウィンアドベンチャーをつくろう①'],
            ['school_class_id' => $classB2->id, 'no' => 24, 'title' => 'ハロウィンアドベンチャーをつくろう②'],
            ['school_class_id' => $classB2->id, 'no' => 25, 'title' => '敵キャラクターのAIっぽい動きを考えよう'],
            ['school_class_id' => $classB2->id, 'no' => 26, 'title' => 'クローンを活用した弾幕ゲームをつくろう①'],
            ['school_class_id' => $classB2->id, 'no' => 27, 'title' => 'クローンを活用した弾幕ゲームをつくろう②'],
            ['school_class_id' => $classB2->id, 'no' => 28, 'title' => 'スコアランキングを表示しよう'],
            ['school_class_id' => $classB2->id, 'no' => 29, 'title' => 'サウンド・BGMで演出を工夫しよう'],
            ['school_class_id' => $classB2->id, 'no' => 30, 'title' => 'クリスマスミニゲームをつくろう①'],
            ['school_class_id' => $classB2->id, 'no' => 31, 'title' => 'クリスマスミニゲームをつくろう②'],
            ['school_class_id' => $classB2->id, 'no' => 32, 'title' => '2学期発表会'],
            // 3学期
            ['school_class_id' => $classB2->id, 'no' => 33, 'title' => '新年オリジナルゲームのアイデア出し'],
            ['school_class_id' => $classB2->id, 'no' => 34, 'title' => 'リストと条件分岐の総復習'],
            ['school_class_id' => $classB2->id, 'no' => 35, 'title' => 'オリジナルゲーム制作①（企画）'],
            ['school_class_id' => $classB2->id, 'no' => 36, 'title' => 'オリジナルゲーム制作②'],
            ['school_class_id' => $classB2->id, 'no' => 37, 'title' => 'オリジナルゲーム制作③'],
            ['school_class_id' => $classB2->id, 'no' => 38, 'title' => 'オリジナルゲーム制作④'],
            ['school_class_id' => $classB2->id, 'no' => 39, 'title' => 'オリジナルゲーム制作⑤（仕上げ）'],
            ['school_class_id' => $classB2->id, 'no' => 40, 'title' => '発表準備＆リハーサル'],
            ['school_class_id' => $classB2->id, 'no' => 41, 'title' => '1年間のふりかえり'],
            ['school_class_id' => $classB2->id, 'no' => 42, 'title' => '1年間の集大成発表会'],
            // B3クラス（応用クラス3組）
            // 1学期
            ['school_class_id' => $classB3->id, 'no' => 1, 'title' => '応用クラス3組オリエンテーション＆前年の復習'],
            ['school_class_id' => $classB3->id, 'no' => 2, 'title' => 'アルゴリズムってなに？（整列・探索を体験）①'],
            ['school_class_id' => $classB3->id, 'no' => 3, 'title' => 'アルゴリズムってなに？（整列・探索を体験）②'],
            ['school_class_id' => $classB3->id, 'no' => 4, 'title' => 'リストを活用したデータ管理①'],
            ['school_class_id' => $classB3->id, 'no' => 5, 'title' => 'リストを活用したデータ管理②'],
            ['school_class_id' => $classB3->id, 'no' => 6, 'title' => '複数スプライトの高度な連携①'],
            ['school_class_id' => $classB3->id, 'no' => 7, 'title' => '複数スプライトの高度な連携②'],
            ['school_class_id' => $classB3->id, 'no' => 8, 'title' => 'タワーディフェンスゲームをつくろう①'],
            ['school_class_id' => $classB3->id, 'no' => 9, 'title' => 'タワーディフェンスゲームをつくろう②'],
            ['school_class_id' => $classB3->id, 'no' => 10, 'title' => 'タワーディフェンスゲームをつくろう③'],
            ['school_class_id' => $classB3->id, 'no' => 11, 'title' => 'UI（メニュー画面）をつくろう'],
            ['school_class_id' => $classB3->id, 'no' => 12, 'title' => 'セーブ・ロードの仕組みを考えよう'],
            ['school_class_id' => $classB3->id, 'no' => 13, 'title' => 'サウンド設計にこだわろう'],
            ['school_class_id' => $classB3->id, 'no' => 14, 'title' => '1学期の作品を仕上げよう'],
            ['school_class_id' => $classB3->id, 'no' => 15, 'title' => '1学期発表会'],
            // 2学期
            ['school_class_id' => $classB3->id, 'no' => 16, 'title' => '夏休みの成果を共有しよう'],
            ['school_class_id' => $classB3->id, 'no' => 17, 'title' => '物理演算っぽい動きに挑戦①（重力）'],
            ['school_class_id' => $classB3->id, 'no' => 18, 'title' => '物理演算っぽい動きに挑戦②（反射・衝突）'],
            ['school_class_id' => $classB3->id, 'no' => 19, 'title' => '対戦ゲームの仕組みを考えよう①'],
            ['school_class_id' => $classB3->id, 'no' => 20, 'title' => '対戦ゲームの仕組みを考えよう②'],
            ['school_class_id' => $classB3->id, 'no' => 21, 'title' => '対戦ゲームの仕組みを考えよう③'],
            ['school_class_id' => $classB3->id, 'no' => 22, 'title' => 'ハロウィンイベント企画＆実装①'],
            ['school_class_id' => $classB3->id, 'no' => 23, 'title' => 'ハロウィンイベント企画＆実装②'],
            ['school_class_id' => $classB3->id, 'no' => 24, 'title' => 'スコア・ランキングシステムを強化しよう'],
            ['school_class_id' => $classB3->id, 'no' => 25, 'title' => 'マイブロックでコードを整理しよう'],
            ['school_class_id' => $classB3->id, 'no' => 26, 'title' => 'アニメーションにこだわろう①'],
            ['school_class_id' => $classB3->id, 'no' => 27, 'title' => 'アニメーションにこだわろう②'],
            ['school_class_id' => $classB3->id, 'no' => 28, 'title' => 'レベルデザインを考えよう①'],
            ['school_class_id' => $classB3->id, 'no' => 29, 'title' => 'レベルデザインを考えよう②'],
            ['school_class_id' => $classB3->id, 'no' => 30, 'title' => 'クリスマスミニゲームコンテスト準備①'],
            ['school_class_id' => $classB3->id, 'no' => 31, 'title' => 'クリスマスミニゲームコンテスト準備②'],
            ['school_class_id' => $classB3->id, 'no' => 32, 'title' => '2学期発表会'],
            // 3学期
            ['school_class_id' => $classB3->id, 'no' => 33, 'title' => '新年の目標をゲームで表現しよう'],
            ['school_class_id' => $classB3->id, 'no' => 34, 'title' => 'アルゴリズムとリストの総復習'],
            ['school_class_id' => $classB3->id, 'no' => 35, 'title' => 'オリジナルゲーム企画書をつくろう'],
            ['school_class_id' => $classB3->id, 'no' => 36, 'title' => 'オリジナルゲーム制作①'],
            ['school_class_id' => $classB3->id, 'no' => 37, 'title' => 'オリジナルゲーム制作②'],
            ['school_class_id' => $classB3->id, 'no' => 38, 'title' => 'オリジナルゲーム制作③'],
            ['school_class_id' => $classB3->id, 'no' => 39, 'title' => 'オリジナルゲーム制作④（仕上げ）'],
            ['school_class_id' => $classB3->id, 'no' => 40, 'title' => '発表準備＆リハーサル'],
            ['school_class_id' => $classB3->id, 'no' => 41, 'title' => '1年間のふりかえり'],
            ['school_class_id' => $classB3->id, 'no' => 42, 'title' => '1年間の集大成発表会'],
            // B4クラス（応用クラス4組）
            // 1学期
            ['school_class_id' => $classB4->id, 'no' => 1, 'title' => '応用クラス4組オリエンテーション＆スクラッチ総仕上げ'],
            ['school_class_id' => $classB4->id, 'no' => 2, 'title' => 'フローチャートで考え方を整理しよう①'],
            ['school_class_id' => $classB4->id, 'no' => 3, 'title' => 'フローチャートで考え方を整理しよう②'],
            ['school_class_id' => $classB4->id, 'no' => 4, 'title' => 'アルゴリズム応用①（探索アルゴリズム）'],
            ['school_class_id' => $classB4->id, 'no' => 5, 'title' => 'アルゴリズム応用②（並び替えアルゴリズム）'],
            ['school_class_id' => $classB4->id, 'no' => 6, 'title' => 'リストと関数っぽいブロックの活用①'],
            ['school_class_id' => $classB4->id, 'no' => 7, 'title' => 'リストと関数っぽいブロックの活用②'],
            ['school_class_id' => $classB4->id, 'no' => 8, 'title' => '本格RPGをつくろう①'],
            ['school_class_id' => $classB4->id, 'no' => 9, 'title' => '本格RPGをつくろう②'],
            ['school_class_id' => $classB4->id, 'no' => 10, 'title' => '本格RPGをつくろう③'],
            ['school_class_id' => $classB4->id, 'no' => 11, 'title' => '本格RPGをつくろう④'],
            ['school_class_id' => $classB4->id, 'no' => 12, 'title' => 'セーブ機能・変数管理を工夫しよう'],
            ['school_class_id' => $classB4->id, 'no' => 13, 'title' => 'デバッグ実践（バグを見つけて直そう）'],
            ['school_class_id' => $classB4->id, 'no' => 14, 'title' => '1学期の作品を仕上げよう'],
            ['school_class_id' => $classB4->id, 'no' => 15, 'title' => '1学期発表会'],
            // 2学期
            ['school_class_id' => $classB4->id, 'no' => 16, 'title' => '夏休みの成果を共有しよう'],
            ['school_class_id' => $classB4->id, 'no' => 17, 'title' => '疑似コード（プログラムの設計図）を書いてみよう①'],
            ['school_class_id' => $classB4->id, 'no' => 18, 'title' => '疑似コード（プログラムの設計図）を書いてみよう②'],
            ['school_class_id' => $classB4->id, 'no' => 19, 'title' => '対戦ゲームをつくろう①'],
            ['school_class_id' => $classB4->id, 'no' => 20, 'title' => '対戦ゲームをつくろう②'],
            ['school_class_id' => $classB4->id, 'no' => 21, 'title' => '対戦ゲームをつくろう③'],
            ['school_class_id' => $classB4->id, 'no' => 22, 'title' => '物理演算に挑戦①'],
            ['school_class_id' => $classB4->id, 'no' => 23, 'title' => '物理演算に挑戦②'],
            ['school_class_id' => $classB4->id, 'no' => 24, 'title' => 'ハロウィンイベントを企画・実装しよう①'],
            ['school_class_id' => $classB4->id, 'no' => 25, 'title' => 'ハロウィンイベントを企画・実装しよう②'],
            ['school_class_id' => $classB4->id, 'no' => 26, 'title' => 'UI・演出にこだわろう①'],
            ['school_class_id' => $classB4->id, 'no' => 27, 'title' => 'UI・演出にこだわろう②'],
            ['school_class_id' => $classB4->id, 'no' => 28, 'title' => 'レベルデザイン＆バランス調整'],
            ['school_class_id' => $classB4->id, 'no' => 29, 'title' => 'マイブロックで大規模プロジェクトを整理しよう'],
            ['school_class_id' => $classB4->id, 'no' => 30, 'title' => 'クリスマスミニゲームコンテスト準備①'],
            ['school_class_id' => $classB4->id, 'no' => 31, 'title' => 'クリスマスミニゲームコンテスト準備②'],
            ['school_class_id' => $classB4->id, 'no' => 32, 'title' => '2学期発表会'],
            // 3学期
            ['school_class_id' => $classB4->id, 'no' => 33, 'title' => 'テキストプログラミングってなに？（Pythonへの橋渡し）'],
            ['school_class_id' => $classB4->id, 'no' => 34, 'title' => 'アルゴリズムとフローチャートの総復習'],
            ['school_class_id' => $classB4->id, 'no' => 35, 'title' => '卒業制作テーマ決め＆企画書づくり'],
            ['school_class_id' => $classB4->id, 'no' => 36, 'title' => 'オリジナルゲーム制作①'],
            ['school_class_id' => $classB4->id, 'no' => 37, 'title' => 'オリジナルゲーム制作②'],
            ['school_class_id' => $classB4->id, 'no' => 38, 'title' => 'オリジナルゲーム制作③'],
            ['school_class_id' => $classB4->id, 'no' => 39, 'title' => 'オリジナルゲーム制作④（仕上げ）'],
            ['school_class_id' => $classB4->id, 'no' => 40, 'title' => '発表準備＆リハーサル'],
            ['school_class_id' => $classB4->id, 'no' => 41, 'title' => '1年間のふりかえり'],
            ['school_class_id' => $classB4->id, 'no' => 42, 'title' => '1年間の集大成発表会'],
            // B5クラス（応用クラス5組）
            // 1学期
            ['school_class_id' => $classB5->id, 'no' => 1, 'title' => '応用クラス5組オリエンテーション＆Pythonにふれてみよう'],
            ['school_class_id' => $classB5->id, 'no' => 2, 'title' => 'Pythonの基本ルールを学ぼう（print文）'],
            ['school_class_id' => $classB5->id, 'no' => 3, 'title' => '変数をつかってみよう①'],
            ['school_class_id' => $classB5->id, 'no' => 4, 'title' => '変数をつかってみよう②'],
            ['school_class_id' => $classB5->id, 'no' => 5, 'title' => '入力（input）をつかってみよう'],
            ['school_class_id' => $classB5->id, 'no' => 6, 'title' => '計算プログラムをつくろう①（電卓）'],
            ['school_class_id' => $classB5->id, 'no' => 7, 'title' => '計算プログラムをつくろう②'],
            ['school_class_id' => $classB5->id, 'no' => 8, 'title' => '条件分岐（if文）を学ぼう①'],
            ['school_class_id' => $classB5->id, 'no' => 9, 'title' => '条件分岐（if文）を学ぼう②'],
            ['school_class_id' => $classB5->id, 'no' => 10, 'title' => '条件分岐を使ったクイズをつくろう①'],
            ['school_class_id' => $classB5->id, 'no' => 11, 'title' => '条件分岐を使ったクイズをつくろう②'],
            ['school_class_id' => $classB5->id, 'no' => 12, 'title' => '繰り返し（for文）を学ぼう①'],
            ['school_class_id' => $classB5->id, 'no' => 13, 'title' => '繰り返し（for文）を学ぼう②'],
            ['school_class_id' => $classB5->id, 'no' => 14, 'title' => '1学期の作品を仕上げよう'],
            ['school_class_id' => $classB5->id, 'no' => 15, 'title' => '1学期発表会'],
            // 2学期
            ['school_class_id' => $classB5->id, 'no' => 16, 'title' => '夏休みの思い出をプログラムで表現しよう'],
            ['school_class_id' => $classB5->id, 'no' => 17, 'title' => '繰り返し（while文）を学ぼう'],
            ['school_class_id' => $classB5->id, 'no' => 18, 'title' => 'リスト（配列）を学ぼう①'],
            ['school_class_id' => $classB5->id, 'no' => 19, 'title' => 'リスト（配列）を学ぼう②'],
            ['school_class_id' => $classB5->id, 'no' => 20, 'title' => 'リストを使ったデータ処理①'],
            ['school_class_id' => $classB5->id, 'no' => 21, 'title' => 'リストを使ったデータ処理②'],
            ['school_class_id' => $classB5->id, 'no' => 22, 'title' => '文字列操作を学ぼう①'],
            ['school_class_id' => $classB5->id, 'no' => 23, 'title' => '文字列操作を学ぼう②'],
            ['school_class_id' => $classB5->id, 'no' => 24, 'title' => 'ハロウィン診断プログラムをつくろう①'],
            ['school_class_id' => $classB5->id, 'no' => 25, 'title' => 'ハロウィン診断プログラムをつくろう②'],
            ['school_class_id' => $classB5->id, 'no' => 26, 'title' => 'じゃんけんゲームをつくろう①'],
            ['school_class_id' => $classB5->id, 'no' => 27, 'title' => 'じゃんけんゲームをつくろう②'],
            ['school_class_id' => $classB5->id, 'no' => 28, 'title' => '数当てゲームをつくろう①'],
            ['school_class_id' => $classB5->id, 'no' => 29, 'title' => '数当てゲームをつくろう②'],
            ['school_class_id' => $classB5->id, 'no' => 30, 'title' => 'クリスマスカウントダウンプログラムをつくろう'],
            ['school_class_id' => $classB5->id, 'no' => 31, 'title' => '2学期の作品を仕上げよう'],
            ['school_class_id' => $classB5->id, 'no' => 32, 'title' => '2学期発表会'],
            // 3学期
            ['school_class_id' => $classB5->id, 'no' => 33, 'title' => '新年の目標管理プログラムをつくろう'],
            ['school_class_id' => $classB5->id, 'no' => 34, 'title' => '条件分岐・繰り返しの総復習'],
            ['school_class_id' => $classB5->id, 'no' => 35, 'title' => 'オリジナルプログラム企画会議'],
            ['school_class_id' => $classB5->id, 'no' => 36, 'title' => 'オリジナルプログラム制作①'],
            ['school_class_id' => $classB5->id, 'no' => 37, 'title' => 'オリジナルプログラム制作②'],
            ['school_class_id' => $classB5->id, 'no' => 38, 'title' => 'オリジナルプログラム制作③'],
            ['school_class_id' => $classB5->id, 'no' => 39, 'title' => 'オリジナルプログラム制作④（仕上げ）'],
            ['school_class_id' => $classB5->id, 'no' => 40, 'title' => '発表準備＆リハーサル'],
            ['school_class_id' => $classB5->id, 'no' => 41, 'title' => '1年間のふりかえり'],
            ['school_class_id' => $classB5->id, 'no' => 42, 'title' => '1年間の集大成発表会'],
            // B6クラス（応用クラス6組）
            // 1学期
            ['school_class_id' => $classB6->id, 'no' => 1, 'title' => '応用クラス6組オリエンテーション＆Python再確認'],
            ['school_class_id' => $classB6->id, 'no' => 2, 'title' => '関数（def）を学ぼう①'],
            ['school_class_id' => $classB6->id, 'no' => 3, 'title' => '関数（def）を学ぼう②'],
            ['school_class_id' => $classB6->id, 'no' => 4, 'title' => '関数を使ったプログラムをつくろう①'],
            ['school_class_id' => $classB6->id, 'no' => 5, 'title' => '関数を使ったプログラムをつくろう②'],
            ['school_class_id' => $classB6->id, 'no' => 6, 'title' => 'リストと関数を組み合わせよう①'],
            ['school_class_id' => $classB6->id, 'no' => 7, 'title' => 'リストと関数を組み合わせよう②'],
            ['school_class_id' => $classB6->id, 'no' => 8, 'title' => '辞書（dictionary）を学ぼう①'],
            ['school_class_id' => $classB6->id, 'no' => 9, 'title' => '辞書（dictionary）を学ぼう②'],
            ['school_class_id' => $classB6->id, 'no' => 10, 'title' => '簡易データベースをつくろう①（成績管理）'],
            ['school_class_id' => $classB6->id, 'no' => 11, 'title' => '簡易データベースをつくろう②'],
            ['school_class_id' => $classB6->id, 'no' => 12, 'title' => 'エラー処理（try文）を学ぼう'],
            ['school_class_id' => $classB6->id, 'no' => 13, 'title' => 'デバッグ実践（バグを見つけて直そう）'],
            ['school_class_id' => $classB6->id, 'no' => 14, 'title' => '1学期の作品を仕上げよう'],
            ['school_class_id' => $classB6->id, 'no' => 15, 'title' => '1学期発表会'],
            // 2学期
            ['school_class_id' => $classB6->id, 'no' => 16, 'title' => '夏休みの成果を共有しよう'],
            ['school_class_id' => $classB6->id, 'no' => 17, 'title' => 'モジュールを使ってみよう①（random）'],
            ['school_class_id' => $classB6->id, 'no' => 18, 'title' => 'モジュールを使ってみよう②（time）'],
            ['school_class_id' => $classB6->id, 'no' => 19, 'title' => 'テキストRPGをつくろう①'],
            ['school_class_id' => $classB6->id, 'no' => 20, 'title' => 'テキストRPGをつくろう②'],
            ['school_class_id' => $classB6->id, 'no' => 21, 'title' => 'テキストRPGをつくろう③'],
            ['school_class_id' => $classB6->id, 'no' => 22, 'title' => 'テキストRPGをつくろう④'],
            ['school_class_id' => $classB6->id, 'no' => 23, 'title' => '診断プログラムをつくろう①'],
            ['school_class_id' => $classB6->id, 'no' => 24, 'title' => '診断プログラムをつくろう②'],
            ['school_class_id' => $classB6->id, 'no' => 25, 'title' => 'クラス（オブジェクト指向）の入り口にふれてみよう①'],
            ['school_class_id' => $classB6->id, 'no' => 26, 'title' => 'クラス（オブジェクト指向）の入り口にふれてみよう②'],
            ['school_class_id' => $classB6->id, 'no' => 27, 'title' => 'ファイル入出力を学ぼう①'],
            ['school_class_id' => $classB6->id, 'no' => 28, 'title' => 'ファイル入出力を学ぼう②'],
            ['school_class_id' => $classB6->id, 'no' => 29, 'title' => '簡易チャットボットをつくろう①'],
            ['school_class_id' => $classB6->id, 'no' => 30, 'title' => '簡易チャットボットをつくろう②'],
            ['school_class_id' => $classB6->id, 'no' => 31, 'title' => '2学期の作品を仕上げよう'],
            ['school_class_id' => $classB6->id, 'no' => 32, 'title' => '2学期発表会'],
            // 3学期
            ['school_class_id' => $classB6->id, 'no' => 33, 'title' => '卒業制作テーマ決め＆企画書づくり'],
            ['school_class_id' => $classB6->id, 'no' => 34, 'title' => 'これまでの総復習（関数・リスト・辞書）'],
            ['school_class_id' => $classB6->id, 'no' => 35, 'title' => '卒業制作①'],
            ['school_class_id' => $classB6->id, 'no' => 36, 'title' => '卒業制作②'],
            ['school_class_id' => $classB6->id, 'no' => 37, 'title' => '卒業制作③'],
            ['school_class_id' => $classB6->id, 'no' => 38, 'title' => '卒業制作④'],
            ['school_class_id' => $classB6->id, 'no' => 39, 'title' => '卒業制作⑤（仕上げ）'],
            ['school_class_id' => $classB6->id, 'no' => 40, 'title' => '発表準備＆リハーサル'],
            ['school_class_id' => $classB6->id, 'no' => 41, 'title' => '1年間のふりかえり'],
            ['school_class_id' => $classB6->id, 'no' => 42, 'title' => '1年間の集大成発表会（卒業制作お披露目）'],
        ];

        foreach ($lessonPlans as $lessonPlan) {
            LessonPlan::create($lessonPlan);
        }
    }
}
